version: 2.1

install_aws_cli: &install_aws_cli
  name: Install AWS CLI
  command: |
    sudo apt-get update -y
    sudo apt-get install -y awscli
    export PATH=$PATH:$HOME/.local/bin
    export AWS_DEFAULT_REGION=us-west-2

workflows:
  build:
    jobs:
      - build:
          context: Appcues

jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.10.3
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix hex.organization auth appcues --key $HEX_API_KEY
      - run:
          <<: *install_aws_cli

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run: mix do deps.get, compile
      - run: mix format --check-formatted
      - run: MIX_ENV=dev mix dialyzer
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"

      - run: mix test

      - store_test_results:
          # Read more: https://circleci.com/docs/2.0/collect-test-data/
          path: _build/test/lib/opscues_config # Replace with the name of your :app
